production:
  database: app2071501
  capsize: <%= 12.megabytes %>
  host: staff.mongohq.com
  port: 10039
  replica_set: true
  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
